PayButton/paybutton

react/src/components/Widget/Widget.tsx

Removing what I believe are superfluous api calls in the Widget component. Its parent component already has a similar function and passes the price data to Widget as a prop, so seems unnecessary here

Prevent extra price api calls

---

docs/package.json

Description: switch dev docs to port 3001
Test Plan: inside docs folder, `npm run serve`, should run docsify on port 3001

fix(issue-157): switch docsify to port 3001

---

.github/renovate.json

Description: adds basic renovate config, setting automerge as false for now, and number of concurrent PRs to 2, as to keep up with review.

chore(issue-161): add basic renovate config

---

react/src/components/Button/Button.tsx
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx

Passing the animation prop to the widget so it can be applied to the widget button. Before it wasn't getting through, so the widget button was always on 'slide'
Test plan: check the animation option is being properly applied to widget buttons

Pass animation to widget component

---

react/src/components/PayButton/PayButton.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/api-client.ts
react/src/util/satoshis.ts

BCH functionality should remain intact - but `BITS` and `SATS` have been removed as currency types

Issue 152 - adding support for XEC - Remove sats and bits as currencies

---

react/src/components/PaymentDialog/PaymentDialog.tsx

`currency` was being imported from the wrong file, presumably it just wasn't caught in the `currency` refactor. This was causing a failure to `npm run build` in the react folder.
Test Plan:
- run `npm run build && npm start` in the react folder. The project and storybook should build.
- Everything related to `currency` should work fine in the `paymentDialog` section on storybook

Fix paymentDialogs build error

---

react/src/hooks/useAddressDetails.ts

In the validation, we were requiring that the address should be a valid xec AND cash address at the same time, that makes no sense, I believe we wanted to validate if it was a valid xec OR a valid cash address.

polling back online

---

react/.env
react/src/components/PayButton/PayButton.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/address.ts
react/src/util/api-client.ts
react/src/util/format.ts
react/src/util/satoshis.ts

This branch actually adds XEC support. Additionally, it (hopefully) finishes the job of converting all calculations to primary units instead of doing calculations in satoshis
Using a XEC address should change the theme, the QR, button text, etc. Selecting a fiat currency and goal should give the proper XEC and BCH amounts.

Issue 152 - adding support for XEC - Actually add xec support

---

paybutton/src/index.tsx

Logic prevented HTML buttons from rendering if any JS button existed, probably accidental instead of intentional.
To make the testing easy, here is the HTML code to test both buttons, the new minified script should be placed in the same directory of the HTML file:
```
<script src="paybutton.js"></script>
<div class="paybutton" text="sss" to="ecash:qzpm28uted62dfsu40xpkvg7m4nekjrz0q04mpaqya"></div>
<div class="paybutton" text="bbb"  to="ecash:qzpm28uted62dfsu40xpkvg7m4nekjrz0q04mpaqya"></div>
<div id="my_button"></div>
<div id="my_button2"></div>
<script>
function mySuccessFunction(txid, amount) {
console.log( { txid, amount } );
}
function myTransactionFunction(txid, amount) {
console.log( 'Received: ' + amount );
}
var config = {
to: …
```

[Issue #176] bug: html and js buttons rendered in the same page

---

.gitignore
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/api-client.ts

Description:
When opening the network tab and opening the qrcode Widget either by:
1. clicking on any child of the menu on the left `Paybutton` and then clicking on the button on the right
2. clicking on any child of the menu on the left `Widget`
You can see that, after 3 seconds, requests for the transactions endpoint were made in duplicate before this PR, on this branch this is solved and only 1 request is made each time.
Test plan:
Described above.
We were creating the hook `useAddressDetails` twice, once in the parent `WidgetContainer` and again in the child `Widget`, since we have a page with the child and not the parent (2.) and another one with both (1.), I made an optional parameter when creating the child that allows the child only to have this hook and update the parent (if …

[Issue #151] fix: transaction api called twice

---

.github/pull_request_template.md
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/hooks/useAddressDetails.ts
react/src/util/api-client.ts

Related to #218
Description
---
Fixes the toast effect.
Test plan
---
Create a button with one of your addresses and send some XEC to it to check if the effect arrives as expected
**Right now there is a problem in the prod server where the server stops registering new txs**. This won't be much testable until this is fixed.
Remarks
---
The client was still expecting the response of the `api/address/transaction/[addr]`  to be formatted as grpc. This goes on to fix the expectation to the new standardized format.

[Issue #218] fix: toast when payment received

---

paybutton-config.json
react/src/util/api-client.ts

Related to #223
Description
---
Makes so that the configuration of the API URL is also set on `paybutton-config.json`.
Test plan
---
Change the values set to default to e.g.:
```
{
"wsBaseURL": "http://localhost:5000",
"apiBaseURL": "http://localhost:3000",
"apiPriceBaseURL": "http://localhost:3000"
}
```
...and check if the changes are now reflected into the button looking for data in the localhost server.

feat: using config file to API urls

---

paybutton/src/index.tsx

Related to #224
Description
---
Fixes the problem where the `on-success` and `on-transaction` attributes of a HTML paybutton wouldn't work.
Test plan
---
Create and HTML paybutton with said attributes and check if they fire as they should. (`onSuccess` fires when the amount is equal to the expected, `onTransaction` fires regardless of the amount).

fix: callbacks for html paybutton

---

react/src/components/Widget/Widget.tsx

Related to #
Description
---
Fix issue where button with no amounts would lead to opening the cashtab extension with no address.
Test plan
---
With the new paybutton.js buttons that have no amount should open the cashtab extension normally with the button address.

fix: if no amount on button, use 0

---

paybutton/src/index.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/randomizeSats.ts
react/src/util/satoshis.ts

Related to #247
Description
---
Makes so that the `random-satoshis` option works well for both XEC and BCH, also makes `true` the default for it.
Test plan
---
1. Unless `random-satoshis="false"` is explicitly set, should be true.
2. For BCH and XEC, the last 4 digits should be ignored and randomized. This means the end should vary from `0.00000000` to `0.00009999` with BCH and from `0.00` to `99.99` on XEC.

[#247] fix: random satoshis for both currencies

---

react/src/components/PayButton/PayButton.tsx

Related to https://github.com/PayButton/paybutton-server/issues/669
Description
---
Fixes the issue where changing the `hoverText` input field on the button generator wouldn't reflect on the button Preview.
Test plan
---
Since this was breaking the server generator, testing is a bit clumsy:
- Build the react module with `cd react && npm run build`
- On the **server** directory, go to `paybutton-server/node_modules/@paybutton/react`, delete everything, and then paste the content of this repo's `react/` folder. Something like `cp paybutton/react/* paybutton-server/node_modules/@paybutton/react/`
- Go to the localhost and try the button generator. The issue should be gone.
PS: The default text `Send Payment` should work normally. It is set on the `Button` component and it was being …

[S#669] fix: remove redundant breaking hovertext default setting

---

react/src/components/Widget/Widget.tsx

Related to #262
Description
---
Fixes #262 and also fixes the second problem where the amount after opening cashtab would not be randomized.
Test plan
---
With this `paybutton.js`, opening the cashtab app after clicking "Send with XEC wallet" should have the correct amount set.
Also a button with no amount set should continue to open cashtab with nothing in the amount filled.

[#262] fix: no comma in amount & randomized amount in cashtab

---

react/src/util/api-client.ts

Related to https://github.com/PayButton/paybutton-server/issues/675
Description
---
Makes so that we only care about new unconfirmed txs.
Since right now the client is not broadcasting incoming confirmed txs, this would be innocuous.  https://github.com/PayButton/paybutton-server/pull/676 will make so that confirmed txs are broadcasted (in order to update the txs for users seeing the button detail view in the server), so this should be released before https://github.com/PayButton/paybutton-server/pull/676 is live. 
Test plan
---
Should work just as before.

[S#675] fix: only care about incoming unconfirmed txs

---

react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx

Depends on
---
Description
---
Changes so that the behavior of the `onSuccess` and `onTransaction` functions is:
`onSuccess`: fires if the incoming transaction amount is the same of the button. If no amount is set, never fires.
onTransaction: fires in all other cases
Test plan
---
Check that the behavior described above is correct for buttons with or without amount.

feat: onSuccess and onTransaction do not fire both

---

react/src/components/Widget/WidgetContainer.tsx

Related to #273
Description
---
Fixes #273 
Test plan
---
Create a button with a fiat `currency` e.g. `currency="CAD"`. Then, after making a payment, make sure `onSuccess` and `onTransaction` are being distinguished.

[#273] fix: fiat amount mistakenly checked

---

react/src/themes/index.tsx

Related to #282
Description
---
Solves #282 
Test plan
---
Create JS & HTML  paybuttons for XEC & BCH and try changing only one or two colors with e.g:
HTML:
```
theme='{ "palette": { "primary": "#00f" } }'
```
JS:
```
theme: {
palette: {
secondary: '#ff0',
tertiary: '#f00',
}
},
```
... and make sure that only that color changes and the others remain set to default.

[#282] fix: use default pallete for each colors

---

paybutton/src/index.tsx
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/randomizeSats.ts
react/src/util/satoshis.ts

Related to #281
Description
---
Allows random satoshis to be a number.
Test plan
---
Create buttons with different `randomSatoshis` values and check the following behavior:
`false`: no random satoshis
`true`: randomize the last 3 digits
`0`: no random satoshis (same as false)
`1`: randomize the last 1 digit
`2`: randomize the last 2 digits
`3`: randomize the last 3 digits
`4`: randomize the last 4 digits
`> 4`: randomize the last 4 digits
Also, check that if a button amount has fewer significant digits than what is being randomized, the randomSatoshis behaves as the biggest that makes sense to that amount, e.g:
`amount=1.00` and `randomSatoshis=4` should behave the same as if `randomSatoshis=3`, since there are only 3 digits that could be randomized in the amount.

[#281] feat: buffed random satoshis

---

react/src/components/Widget/Widget.tsx

Related to #290
Description
---
Fixing the font-size for the widget footer not being specified
Test plan
---
Preview the widget and check the footer link is the right size even if other css rules trying to target it 
for example try adding  <style>
body a {
font-size: 44px !important;
color: red !important;
}
</style>

Add widget style rule

---

react/src/components/Widget/Widget.tsx

Related to #141
Description
---
This should add the amount to the copied address when you click the qr code
It should also use the converted XEC amount if a non-xec currency is specified 
Test plan
---
Build the package and test out a widget and a button with and without an amount specified, and try changing the currency as well
Then try pasting the copied value into different wallets and see if the amount field is carried through correctly

[#141] UI: Add amount to click to copy

---

react/src/components/Widget/Widget.tsx

Related to #306
Description
---
Fix UI bug where the loading circle would appear on the bar even if there was no bar to be loaded (when there is no goal)

[#306] fix: no loading if no goal bar to be loaded

---

react/package.json

Description
---
Solves issue where if `dist/src`  was not created the build would error.

fix: only move files if they exist

---

paybutton/src/index.tsx
react/package.json
react/src/components/Widget/Widget.tsx

Related to #289
Depends on
---
Description
---
Fixed issue where Widgets QR codes  did not get rerendered if the address  changed.
Test plan
---
Use the function `PayButton.renderWidget` to rerender an HTML element and make sure it works.

[#289] fix: widget container renderization

---

react/src/components/Widget/Widget.tsx

Description
---
Widget amount wouldn't update upon re render. This should fix it.
Test plan
---
Create a `paybutton-widget ` and use JS to change its amount, make sure the change is reflected in the send text and the QR code.

fix: widget amount update

---

react/src/components/Widget/Widget.tsx

Related to #
Description
---
Adding a useEffect hook to listen for props.amount change so the amount and widget get updated when the amount changes 
Test plan
---
Build and test it out. Check the amount changes when updated, especially in a react build where the amount is a passed state variable. Can see https://ecash.land/ as an example with this patch

Fix: Update amount in widget React 

---

react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx

Related to #317
Description
---
Solves #317 
Test plan
---
Make sure that after changing the address of a widget:
1. The old address, when receiving transactions, doesn't trigger `onSuccess`, `onTransaction`, alert, etc.
2. The new address does.

[#317] fix: address change subscription

---

docs/README.md
docs/zh-cn/README.md
docs/zh-tw/README.md
paybutton/dev/advanced.html
paybutton/src/index.tsx
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/opReturn.ts

Related to #302 
Description
---
Allows for a `op-return` parameter.
Test plan
---
This parameter will be prefixed by `paybutton$` and then embedded in the copy + paste URL — CashTab still not supported.
Then, when pasted into ElectrumABC, this should show something like `paybutton$the-data-you-inputted-in-the-op-return-props-attribute`. 
Remarks
---
Parsing of this data will be implemented in a next PR

[#302] feat: op return parameter

---

react/src/components/Widget/Widget.tsx
react/src/util/api-client.ts

Related to #331
Description
---
This issue was happening because the app did not set the load to false when the api call fails, so in this fix we 
add error handling and set the loader to false to fix qrcode not showing up 
Test plan
---
- Run story book using this steps from the [docs](https://docs.paybutton.org/#/?id=developer-quick-start:~:text=of%20the%20project.-,Developer%20Quick%20Start,-Build)
```
> docker-compose up
> Wait for storybook to initialize.
> Open http://localhost:6006.
```
- Open storybook 
- Go to `Paybutton` 
- Set `to` option to a valid BCH address like this one  `bitcoincash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7q9ayphulp` 
- Open the Payment dialog by clicking in the `Paybutton`  and check if the `BCH` `Qrcode`  is showing up as expected

fix: catch api error

---

react/package.json

Related to #346
Description
---
This PR adjusts the version of `notistack` to mach material-ui v4, it fixes the font in the toast
Test plan
---
Open the project, run the command `yarn clean:build` get the build and test if the toast has the correct font

fix: notistack version

---

paybutton/src/index.tsx
paybutton/yarn.lock
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/tests/opReturn.test.ts
react/src/util/opReturn.ts

Related to #302
Depends on
---
Description
---
Adds the `paymentId` to the `PayButton` component to be passed as props to the other components; and as arguments to the `onOpen`  and `onClose` functions.
If no props arrive (as  of when creating just the Widget), the paymentId will be generated randomly in the Widget itself.
Test plan
---
Try to see the paymentId on the `onOpen` and `onClose` functions.

[#302] feat: payment id on components

---

react/src/components/Widget/WidgetContainer.tsx
react/src/util/api-client.ts
react/src/util/opReturn.ts

Related to #302
Depends on
---
Description
---
Uses paymentId to fire `onSuccess`.
Test plan
---
WIP

[#302] feat: payementId on success

---

docs/README.md
docs/zh-cn/README.md
docs/zh-tw/README.md

Related to #357
Description
---
- added parameters to the documentation
Test plan
---
run `yarn start:docs` and check if the documentation on `onOpen` and `onClose` has the paremeters

fix(357): fix documentation

---

react/src/components/PayButton/PayButton.tsx

Related to #363 
Description
---
Updated arg naming in onOpen
Test plan
---
open the project run `yarn build` and make sure the build is working as exepected

feat: update onOpen arg names

---

react/src/components/Widget/Widget.tsx

Related to #367 
Description
---
fix disable_payment_id prop not working
Test plan
---
open the project, run `yarn build` and test the button passing disablePaymentId true like this: 
`disable-payment-id="true"`

fix:disable payment id

---

react/src/components/PaymentDialog/PaymentDialog.tsx
react/src/components/Widget/WidgetContainer.tsx

Related to #369 
Description
---
fix call on-succes conditions
fixed amount not being set correctly after changign
Test plan
---
Open the project run `yarn build` , do a transaction with the amount indicated by the button and it should trigger the onSuccess function you set
Test 1: 
set a button passing the `on-success` function > do the payment > check if the onSuccess function was triggered
Test 2: 
set a widget passing the `on-success` function >  do the payment >  check if the onSuccess function was triggered 
Test 3
set a widget passing the `on-success` function   and set an `amount` > change the amount manually> proceed with the payment >   check if the onSuccess function was triggered

fix(#369): call on-succes

---

package.json

Related to #380 
Description
---
Added the command `start:rollup` to the root of the monorepo
Test plan
---
Open the project, run `start:rollup`

feat: add start rollup command

---

react/src/components/Widget/WidgetContainer.tsx
react/src/util/api-client.ts

Related to https://github.com/PayButton/paybutton-server/issues/811
Description
---
Removes redundant `opReturn`, makes `paymentId` mandatory (if not present, it will be empty) and sends it all to `onSuccess` and `onTransaction`.
Test plan
---
Should be tested with https://github.com/PayButton/paybutton-server/pull/821
Make sure to use
```
{                                      
"wsBaseUrl": "http://localhost:5000",
"apiBaseUrl": "http://localhost:3000"
}                                      
```
... in react/src/paybutton-config.json before building. Then run the server locally, and use the builded .js wherever you prefer to test if  receiveing a tx executes onSuccess /onTransaction without erroring.

[S#811] use simplified tx

---

react/src/components/Widget/Widget.tsx

Description
---
Opening cashtab by clicking the "Send with XYZ Wallet" button should now include the op_return data.
Test plan
---
There are three states to test:
1. PC, with cashtab extension
2. PC, without the extension
3. Mobile
When clicking on the pay button of the PayButton, regardless if the amount is in XEC or in fiat, **1.** and **3.** should open cashtab with the right address, amount and with the OP_RETURN set. **2.** will input BIP21 directly into the browser URL bar. It will then depend on your computer being configured  to have a default program that opens `ecash:` protocol URIs.

fix: cashtab url with op_return_raw parameter

---

docs/README.md
docs/zh-cn/README.md
docs/zh-tw/README.md
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/api-client.ts

Related to #391
Description
---
In order to have `onOpen` use the crypto amount, we have to know the crypto price before opening the button. This is now the case, as we fetch the price just as the component loads.
Test plan
---
- Make sure onOpen works with the crypto amount even if the paybutton is fiat,
- Make sure fiat widgets still work normally; i.e they fetch the price too.

[#391] feat: on open uses crypto amount

---

react/src/util/format.ts
react/src/util/satoshis.ts

Related to #267 
Description
---
added "narrowSymbol" option to formatPrice to use a narrow format symbol ("$100" rather than "US$100").
Test plan
---

feat: add narrowSymbol option to format price

---

react/lib/components/Widget/Widget.tsx

Related to #397 #336 
Description
---
This PR fixes the hoverText property that wasn't being set for the button inside the widget 
Test plan
---
Run `yarn clean:build`  make sure widget hover-text prop works.

fix: widget hover prop

---

react/lib/components/PayButton/PayButton.tsx
react/lib/components/PaymentDialog/PaymentDialog.tsx
react/lib/components/Widget/WidgetContainer.tsx

Related to #336 
Description
---
Fixed hover not working on payment dialog 
Test plan
---
Run `yarn build `  and `yarn dev`
in the dev demo page in` localhost:1001` check the option that has a hover-text set and make sure the hover set is working on the payment dialog.

fix: hover payment dialog

---

docs/package.json
docs/yarn.lock

Related to #261 
Description
---
Added resolutions with docsify pointing to the latest version of it
Test plan
---
Run `yarn start:docs` go to `docs/node_modules/docsify/package.json` and make sure the version is  field is set to `"4.13.1"`

chore: add docsify resolution

---

react/lib/components/PayButton/PayButton.tsx
react/lib/components/PaymentDialog/PaymentDialog.tsx
react/lib/components/Widget/Widget.tsx
react/lib/components/Widget/WidgetContainer.tsx
react/lib/util/address.ts
react/lib/util/api-client.ts
react/lib/util/format.ts
react/lib/util/randomizeSats.ts
react/lib/util/satoshis.ts
react/lib/util/types.ts

Related to #405 
Description
---
This adds a file with the types being used in the codebase 
Test plan
---
yarn build && yarn dev

refactor: add types util

---

react/lib/components/Widget/WidgetContainer.tsx
react/lib/tests/number.test.ts
react/lib/util/number.ts
react/lib/util/satoshis.ts

Related to #405 
Description
---
Added handler with BigNumber logic in utils
Test plan
---
yarn build && yarn dev

refactor: add number util

---

docs/_sidebar.md
docs/zh-cn/_sidebar.md
docs/zh-tw/_sidebar.md

Related to #403 
Description
---
- Just renamed can-edit prop, currently it is called editable
Test plan
---
`yarn start:docs`

docs: rename can edit

---

react/lib/components/Widget/Widget.tsx
react/lib/util/sideshift.ts

Related to #187
Description
---
Adds logic to select coins using SideShift's API, displays their amount and the rate of conversion. 
This PR adds the logic for selecting the amount & currency to pay with, but **it doesn't yet implement the payment itself.** 
E.g, by selecting BTC and clicking "Pay with BTC", nothing will happen aside from a console.log of "WIP".
It's also important to notice that I didn't work in the design of the components, only their functionality. This PR lays ground for a frontend work to be done, with the goal of making the new  stuff more intuitive and agreeable for the eyes. 
Finally, it is also important to notice that this PR is off of a proxy branch, meaning approving and merging it won't commit anything to master (since it's incomplete). Nonetheless, it should …

feat: sideshift integration

---

react/lib/components/Widget/Widget.tsx

Related to #420 
Description
---
Fixed editable prop not working when "false" was given 
Test plan
---
Run the project with yarn clean:build && yarn dev 
create a paybutton with `editable="false"` it should not enable edit box

fix: editable prop

---

react/lib/components/Button/Button.tsx

Related to #428 
Description
---
Added logic to render `<div>&nbsp;</div>` when text is empty string 
Test plan
---
Run the project with yarn dev and test the button with prop text=""

fix: text empty nbsp

---

react/lib/components/Widget/AltpaymentWidget.tsx
react/lib/components/Widget/Widget.tsx

Related to #442
Description
---
- Prevent non numerics in the input
- Improved copy buttons and shift value displays 
- style tweaks
- improve outer gray box jumping around. This one was is kind of tricky due to some of the widget's responsive size definitions for the qr inner content, which is not present here. So its better, but not perfect 
Test plan
---
preview and try out a shift

[UI]: Sideshift ui edits

---

react/lib/components/Widget/AltpaymentWidget.tsx
react/lib/components/Widget/Widget.tsx

Related to #448 
Description
---
Fixed decimals and settleCoin name 
Fixed decimals of settleCoin 
Test plan
---
- Create a paybutton with both BCH/XEC addresses and check the following behavior -> 
go to sideshift > choose a coin > click `Send with sideshift` > set an amount > go back > go back 
check if the amount is set with correct number of decimals.

fix: sideshift amount decimals

---

react/lib/components/Widget/AltpaymentWidget.tsx

Related to #187 
Description
---
Prevent the button in the sideshift flow from being disabled if the paybutton amount is not editable. 
My understanding is 'pairAmount' is not used if 'altpaymentEditable' is not enabled. Its coming in undefined, so just ignoring it if its not altpaymentEditable 
Test plan
---
Try out the sideshift with a editable and non editable amount button

ui: prevent disabled button on non editable amount sideshift

---

react/lib/components/Widget/AltpaymentWidget.tsx
react/lib/components/Widget/Widget.tsx

Related to #
Description
---
Moving the sideshift content to be absolutely positioned so its always the same exact size as the widget to prevent any jumping 
Test plan
---
Try some shifts

ui: Make SideShift container same size as widget 

---

react/lib/components/Widget/Widget.tsx

Related to #
Description
---
The button when disabled (aka invisible) was still clickable. Fixing that here
Test plan
---
preview and try clicking an invisible button

fix sideshift button when opacity 0

---

react/lib/components/Widget/AltpaymentWidget.tsx
react/lib/components/Widget/Widget.tsx

Related to #
Description
---
Fixing the font family not being applied on the edit amount ticker and the sideshift button and container
Test plan
---
Preview the site and try changing the body font-family to 'serif' in the inspector and see if the sideshift button changes font or not. (it should not)

ui: fix fonts not coming through

---

react/lib/components/Widget/Widget.tsx

Related to #464 
Description
---
Open cashtab.com when ElectrumABC and Cashtab Extension is not installed 
Test plan
---
Run `yarn dev`, test send button with ElectrumABC and Cashtab Extension not installed

fix: open cashtab web case

---

react/lib/altpayment/index.ts
react/lib/components/Widget/Widget.tsx

Related to #460 
Description
---
Fixed altpayment not showing up when currency is declared 
Test plan
---
create a button with currency set and an amount higher than $10, altpayment option should show up

fix: altpayment not showing up

---

react/lib/components/Widget/WidgetContainer.tsx
react/lib/tests/util/validate.test.ts
react/lib/util/validate.ts

Related to #366 
Description
---
Fix button not triggering success when random satoshis is active 
Test plan
---
1 - Test component(paybutton and widget) with no amount should trigger succes
2 - Test if component (paybutton and widget) with an amount and without random satoshis active is triggering sucess
3 - Test if component (paybutton and widget) with an amount and random satoshis active is triggering success as expected

fix: randomSatoshis trigger success

---

docs/README.md
docs/_sidebar.md
docs/zh-cn/README.md
docs/zh-cn/_sidebar.md
docs/zh-tw/README.md
docs/zh-tw/_sidebar.md
paybutton/dev/demo/paybutton-generator.html
paybutton/src/index.tsx
react/lib/components/PayButton/PayButton.tsx
react/lib/components/PaymentDialog/PaymentDialog.tsx
react/lib/components/Widget/Widget.tsx
react/lib/components/Widget/WidgetContainer.tsx

Related to #270 
Description
---
Added the `transaction-text` prop. The `transaction-text` will be displayed in the widget when a transaction occurs, but the amount does not match the required amount, preventing a success message. 
Test plan
---
- Add transaction-text prop in a paybutton and widget 
- Test transact-text in paybutton generator

feat: transaction text prop

---

.github/coding-instructions.md

Description
---
Adds a general project coding instructions file for Copilot to better understand what we want it (and anyone else working on the project) to do / not do.
This is just a starting point. We want to promptly add things that are specific to our project too (eg. Technologies used, coding standards chosen, etc).
Test plan
---
Try Agent Mode in your editor (eg. VS Code) and make sure Copilot's actually using the instructions.
Remarks
---
Currently, Copilot doesn't always read the instructions file every single time so you will have more luck if you open it in your editor and have it as the context when you're using Agent Mode.

Add Copilot instructions file

---

react/lib/util/cashtab.ts

Related to #537 
Description
---
Use bip21 to open cashtab extension even if there is no amount set
Test plan
---
Create a button with an amount and check if cashtab extension opens, do the same with a button with no amount

fix: open cashtab with no amount

---

react/lib/util/cashtab.ts

Related to #
Description
---
Removed unecessary encoding in the cashtab redirect url 
Test plan
---
Without the cashtab extension installed make sure the cashtab website opens the payment info correctly

fix: redirect cashtab url

---

react/lib/util/chronik.ts
react/yarn.lock

Description
---
Adds `inputAddresses` back to `onSuccess` or `onTransaction` callbacks.
Test plan
---
Make a button with `onTransaction` or `onSuccess` that will `console.log` the whole `tx` argument and make sure it includes the property `inputAddresses` as expected.

fix: input addresses in callback args
