PayButton/paybutton

react/package.json

specify popperjs version without the husky bug

68-revert to working version

---

react/src/components/Widget/Widget.tsx

https://github.com/PayButton/paybutton/issues/47

parse string

---

docs/README.md
docs/darkmode.js
docs/index.html
docs/style.css

https://github.com/PayButton/paybutton/issues/59

59 Improve website dark mode

---

docs/darkmode.js
docs/style.css
react/src/components/Widget/Widget.tsx

https://github.com/PayButton/paybutton/issues/91
this depends on the PR from 
https://github.com/PayButton/paybutton/issues/88
to work properly.
the docs also must point to the newly built paybutton.js on unpkg before seeing changes.

91 Stop website styling from leaking into PayButton widget

---

paybutton/dev/advanced.html
paybutton/dev/default.html
paybutton/dev/html.js
paybutton/dev/widget.html
paybutton/package-lock.json
paybutton/package.json
paybutton/rollup.config.js
paybutton/src/index.tsx
react/src/components/PayButton/PayButton.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx

https://github.com/PayButton/paybutton/issues/88

88 Ensure 'disabled' property works by itself with a valid address entered

---

react/src/components/Button/Button.tsx

https://github.com/PayButton/paybutton/issues/63

63 Stop button from shrinking in width on hover if primary button text is long

---

react/src/components/PayButton/PayButton.tsx
react/src/components/Widget/Widget.tsx

The issue is that it was there to deal with a few build warnings on React side so those are back.

Removed commit that was causing the build to not complete on some systems

---

react/src/components/Widget/WidgetContainer.tsx

replaces  https://github.com/PayButton/paybutton/pull/109

turn sound off with hideToasts

---

docs/zh-cn/README.md
docs/zh-tw/README.md
react/package-lock.json
react/package.json
react/src/components/PayButton/PayButton.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/api-client.ts
react/src/util/format.ts
react/src/util/satoshis.ts

https://github.com/PayButton/paybutton/issues/98
&
https://github.com/PayButton/paybutton/issues/48
for this PR.

48 Add support for 'Bits', like we do 'Sats'

---

docs/style.css

https://github.com/PayButton/paybutton/issues/108

108 Ensure 'language' text and dropdown in docs use the same (dark) font colour as the subtitle (dark mode)

---

react/.eslintrc
react/src/themes/index.tsx

https://github.com/PayButton/paybutton/issues/107

107 Have '#' be optional when specifying colours for the theme

---

react/package-lock.json
react/package.json
react/src/components/Widget/Widget.tsx
react/src/util/api-client.ts

https://github.com/PayButton/paybutton/issues/111

111 Fiat price sometimes changes shortly after the dialog is up

---

paybutton/src/index.tsx
react/src/components/PayButton/PayButton.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/hooks/useAddressDetails.ts
react/src/themes/index.tsx

https://github.com/PayButton/paybutton/issues/75
renders the component 
displays errors
disables button

75 Show better error message in the console when unable to create the button

---

react/src/components/Widget/Widget.tsx

https://github.com/PayButton/paybutton/issues/105

105 Ignore values from bad API calls so we don't get NaNs showing up

---

react/src/components/PayButton/PayButton.stories.tsx
react/src/components/Widget/Widget.stories.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/hooks/useAddressDetails.ts
react/src/util/api-client.ts

replaced rest, so it's important to be thorough to Q/A for issues.

10 Add (optional) server/api with address checking and notifications

---

paybutton/package-lock.json
paybutton/package.json
paybutton/rollup.config.js
react/.env
react/package-lock.json
react/src/util/api-client.ts

Description: adds dynamic `rootUrl` through environment variables to the react component. This adds the ability to build the client with different URLs easily by changing the .env file's `REACT_APP_API_URL` variable.
Example: we can test the client against paybutton-server running locally by setting the .env file to:
`REACT_APP_API_URL=http://localhost:3000/api` and then rebuilding the client.

feat: add dynamic api url through env vars

---

docs/index.html
docs/package-lock.json
docs/package.json

Description: Fix for #155, adding a class definition so docsify correctly parses the widget.
Test Plan: inside docs folder, run `npm run serve`, go to the widget section and check if it's showing up:

fix(issue-155): adds paybutton-widget class definition

---

react/package-lock.json
react/package.json

Using this solution:
https://github.com/storybookjs/storybook/issues/13332#issuecomment-736004964
`cd ./react`
`npm i`
`npm run build`
`npm run storybook`
Should launch storybook without errors.

Repair Storybook Script

---

react/src/components/Button/Button.tsx
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx
react/src/components/Widget/Widget.tsx
react/src/themes/index.tsx
react/src/themes/themes/xec.ts

Added a theme option for eCash that will be automatically applied if an ecash address is detected, but it can be overidden if a custom theme option is entered 
test plan: try using an ecash address and messing with the theme as well

Add eCash theme

---

react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/api-client.ts
react/src/util/satoshis.ts

No functionality change - this is just collating all the places where it lists the currencies, and adding a couple TODOs

 Issue 152 - adding support for XEC - really minor refactor

---

paybutton/.github/pull_request_template.md

Description
---
Creates a template for PRs. Sections that don't apply can always be deleted, just as I did in creating this PR. I take this is easier and less time-consuming than writing it when needed.
Test plan
---
N/A

chore: create PR default template

---

react/src/components/Widget/Widget.tsx
react/src/util/format.ts
react/src/util/satoshis.ts

Description:
---
Fixes the `goal` feature, which was broken. Probably related to the obsolete Currency Formatter lib being used. In their own [github page](https://github.com/smirzaei/currency-formatter): 
This is still being used in other places. I did not care to refactor it all because this would require more work than the necessary to fix the goal issue, but would be a good thing to do post V1.
Test plan:
---
Compile the `paybutton.js` file locally by running `npm run build` first on the `react/` folder and then on the `paybutton/` folder.
Then, create a HTML file e.g:
```
<!DOCTYPE html>
<html>
<head>
<title>lkasdfjaskl</title>
<script src="/home/example-path/client-paybutton/paybutton/dist/paybutton.js">
</script>
</head>
<body>
<h1>Botão</h1>
<div id="botaoo"></div>
<script>
var …
```

[Issue #205] fix: Goal price fix

---

react/.env

Description
---
Removes obsolete env vars that now are in `paybutton-config.json`
Test plan
---
N/A

chore: remove obsolete env vars

---

react/src/components/Button/Button.tsx
react/src/components/Widget/Widget.tsx

Related to #
Description
---
We noticed on one site our styles were being overridden. By adding !important to the styles it can help prevent this
Test plan
---

Add !important to styles

---

paybutton/src/index.tsx

Related to #253 
Description
---
Show widget even if there is no button on the page
Test plan
---
compile and try adding a widget to a site. It should appear regardless of the presence of a button. Can test here https://lovely-starlight-5a510a.netlify.app/

UI: Render widget with no button

---

react/src/components/Widget/WidgetContainer.tsx

Description
---
Show success text when payment is made
Test plan
---
Compile and try sending an amount to a button. You should see 'Thank you!' if no success text is set, or your message if you define one. Can test here https://fancy-wisp-ff1c6b.netlify.app/

UI: Render success text

---

paybutton/package-lock.json
paybutton/package.json
react/package-lock.json
react/package.json

Related to #
Description
---
The `package-lock.json` files were outdated, this simply commits their changes after running `npm install`.
Test plan
---
Nothing should change.

chore: updated package lock

---

paybutton/package.json
react/package.json

Description
---
The project version was only modified in `package-lock.json` files, this also changes in `package.json` files.

fix: version bump also on package.json

---

react/src/components/Widget/Widget.tsx

Related to #296
Description
---
Remove the powered by paybutton link at the bottom of the widget
Test plan
---
Preview a button and check the link is gone and it looks good

[#296] Remove powered by link

---

docs/README.md
docs/_sidebar.md
docs/zh-cn/README.md
docs/zh-cn/_sidebar.md
docs/zh-tw/README.md
docs/zh-tw/_sidebar.md
paybutton/dev/advanced.html
paybutton/package-lock.json
paybutton/src/index.tsx
react/src/components/PayButton/PayButton.stories.tsx
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx

Related to #298
Creates `onOpen` and `onClose` parameters.
Description
---
Test plan
---

feat: onClose and onOpen functions

---

paybutton/package-lock.json
paybutton/package.json
paybutton/rollup.config.js
paybutton/rollup.prod.js
paybutton/src/index.tsx
react/package.json
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx

Related to #294
Description
---
Fixes bug where paybutton wouldn't build due to missing declaration files.
Test plan
---
Build both repos and check if the created js file seems to be normal.

[#294] fix: typescript declaration files

---

react/src/components/Widget/Widget.tsx

Description
---
Fixes bug (visible on ecash.land) where Widget would infinitely rerender.

fix: amount rerendering

---

react/src/components/Widget/Widget.tsx

Description
---
Fix bug where upon opening a paybutton it would randomize the satoshis a second time, make so that the amount seen by `onOpen` and the actual amount on the paybutton would be different.
Test plan
---
On master, try setting a paybutton with `onOpen` and verify that the amounts don't agree. In this branch they should.

feat: thisCurrencyObject logic refactor

---

react/src/components/Widget/Widget.tsx

Related to #320
Description
---
Fixes #320.
Test plan
---
Make a Widget and make sure the `amount` appears correctly without having to rerender it somehow.

[#320] fix: initial addressType

---

react/.storybook/default-args.ts
react/src/components/PayButton/PayButton.stories.tsx
react/src/components/PaymentDialog/PaymentDialog.stories.tsx
react/src/components/Widget/Widget.stories.tsx
react/src/components/Widget/Widget.tsx
react/src/paybutton-config.json

Related to https://github.com/PayButton/paybutton/issues/313
Description
---
- Changed default currency to be XEC instead of BCH 
Test plan
---
Run story book using this [steps](https://docs.paybutton.org/#/?id=developer-quick-start:~:text=of%20the%20project.-,Developer%20Quick%20Start,-Build) 
Check if the components are set to pay with XEC by default

fix: set xec as default currency

---

react/jest.config.js
react/package-lock.json
react/package.json
react/src/tests/opReturn.test.ts

Related to #32
Description
---
Adds `jest` test suite to the project & a sample test.
Test plan
---
`npm run test` inside `react/`
Remarks
---
I had to update typescript in order for it to work

[#32] chore: add jest to project

---

docs/README.md
docs/zh-cn/README.md
docs/zh-tw/README.md

Related to #342
Description
---
Changes from #342 not related to the PR; updates chinese documentation

chore: update chinese docs

---

react/yarn.lock

Related to #348
Description
---
Fixes missing yarn.lock update.
Test plan
---
running `yarn` on `react/` shouldn't create unstaged changes.

[#348] chore: update yarn lock

---

docs/package.json
docs/yarn.lock

Related to #261 
Description
---
Updated docs dependencies 
Test plan
---
open the project and run `yarn start:docs` check if the documentation is rendering as expected

chore: update docs dependencies

---

docs/README.md
docs/zh-cn/README.md
docs/zh-tw/README.md
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx

Related to #359
Description
---
set randomSatoshis to false

fix(359): randomSatoshis false

---

paybutton/src/index.tsx
react/src/components/Widget/Widget.tsx
react/src/components/Widget/WidgetContainer.tsx

Related to #359 
Description
---
- Changed the default randomSatoshi in the widgets
- Updated the validation of randomSatoshi prop what where setting it to true if undefined
Test plan
---
Open the project, run `yarn clean:build`, check if the default randomSatoshi prop of the button is set to false

fix: set randomSatoshi default

---

docs/README.md
docs/zh-cn/README.md
docs/zh-tw/README.md
react/src/components/PayButton/PayButton.tsx
react/src/components/PaymentDialog/PaymentDialog.tsx
react/src/components/Widget/WidgetContainer.tsx
react/src/util/api-client.ts
react/src/util/opReturn.ts

Related to #375  #374 
Description
---
This PR will introduce these fixes: 
- fix set success to true in paymentDialog
- fix calling onSuccess when no amount set 
- Set amount to number in onSuccess callback 
Test plan
---
Open the project, run `yarn build`  and test if onSuccess function is called and if it returns the amount properly
@lissavxo

onSuccess fixes

---

react/lib/components/Widget/Widget.tsx
react/lib/tests/api-client.test.ts
react/lib/util/api-client.ts
react/lib/util/constants.ts
react/lib/util/format.ts
react/lib/util/satoshis.ts

Related to #405 
Description
---
Added constants to a separated file and fixed tests
Test plan
---
yarn build && yarn dev

refactor: add constant util

---

paybutton/dev/demo/index.html
paybutton/dev/demo/paybutton-generator.html
paybutton/dev/demo/style.css

Related to #403 
Description
---
This is a generator that starts with a paybutton declared via html and using `Vue js` it gets prop values from a form  and creates a new button for testing 
This generator was created to help test quickly different props in an isolated button
While working on it we found this issues: 
- props are not working properly when creating a paybutton via html (div with paybutton class), for example: 
- `disable = false ` does disables the button
- `disabe-payment-id = false ` does disable paymentId
- need to check if all props are taking effect on PayButton.render , for example: 
- theme prop does not apply the theme 
Test plan
---
Run `yarn dev` when it runs go to localhost:10001 and go to Generator page. 
test the button that is there
try to add some props and …

feat: paybutton generator dev

---

react/lib/components/Widget/Widget.tsx
react/lib/util/constants.ts

Related to #417 
Description
---
Added logic to add amount to copy url
Test plan
---
Run the project with yarn:clean:build
Create a bch button or widget and copy the qrcode url check if amount is there

fix: amount missing bch qrcode

---

paybutton/dev/demo/index.html

Description
---
Fixes wrong address for localhost button.
Test plan
---
Should fail before but work now.

fix: ws localhost port for demo button that uses localhost always

---

docs/README.md
docs/zh-cn/README.md
docs/zh-tw/README.md

Related to #462 
Description
---
Updated **Advanced Usage** section to reflect the current configurations 
Test plan
---
Run `yarn start:docs` and check **Advanced Usage** section

docs:update advanced usage

---

react/lib/components/PaymentDialog/PaymentDialog.tsx
react/lib/components/Widget/Widget.tsx

Related to #227
Description
---
Adding some subtle animations to the dialog open, qrcode, and buttons
Test plan
---
preview and try it out. Let me know if you see any issues

ui: add animations

---

paybutton/dev/demo/index.html
paybutton/dev/demo/paybutton-generator.html

The goal is to stop sending micropayments to our donation address. The address used here is one we control.
Test plan
---
Launch with `yarn build:dev` and visit `localhost:10001`. Everything should be set to point to that address.
Think about where else we may have addresses that we use for dev purposes in case I may have missed some as we'll want all of them changed.

Only use dev addresses on demo page

---

react/lib/components/Widget/WidgetContainer.tsx

Related to #245 
Description
---
Increased toast margin bottom 
Test plan
---
Make a payment and check if the toast shows up with the margin bottom applied

feat: increase toast margin bottom
